{% set name = "gandlf" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8368667229b29227b1731043554dda34aa10034f20fc03ea3d75a221f13de1b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.12
    - pytorch ==2.3.1
    - black ==23.11.0
    - numpy ==1.25.0
    - scipy
    - simpleitk !=2.0.*
    - torchvision
    - tqdm
    - torchio ==0.19.6
    - pandas >=2.0.0
    - scikit-learn >=0.23.2
    - scikit-image >=0.19.1
    - setuptools
    - seaborn
    - pyyaml ==6.0.1
    - matplotlib-base
    - gdown ==5.1.0
    - pytest
    - coverage
    - pytest-cov
    - psutil
    - medcam
    - opencv
    - torchmetrics ==1.1.2
    - zarr ==2.10.3
    - pydicom
    - onnx
    - torchinfo ==1.7.0
    - segmentation-models-pytorch ==0.3.3
    - acsconv ==0.1.1
    - requests >=2.32.2
    - docker-py
    - dicom-anonymizer ==1.0.12
    - twine
    - keyring
    - monai ==1.3.0
    - click >=8.0.0
    - deprecated
    - packaging ==24.0
    - typer ==0.9.0
    - colorlog
    - opacus ==1.5.2
    - huggingface_hub ==0.25.1
    - openslide >=4.0.0
    - openslide-python ==1.4.1

test:
  imports:
    - GANDLF
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mlcommons.github.io/GaNDLF/
  summary: PyTorch-based framework that handles segmentation/regression/classification using various DL architectures for medical imaging.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mlcommons.github.io/GaNDLF/
  dev_url: https://mlcommons.github.io/GaNDLF/extending/

extra:
  recipe-maintainers:
    - AlexanderGetka-cbica
    - sarthakpati
