{% set name = "gandlf" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CBICA/GaNDLF/archive/{{ version }}.tar.gz
  sha256: 26dd7ebb34cf2fa1747121c0f45ffebe04d9a93783223d51dcf9cb87f95313a4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - torchio ==0.18.57
    - pytorch >=1.7
    - numpy ==1.21.0
    - scipy
    - tqdm
    - pandas
    - pylint
    - scikit-learn >=0.23.2
    - pickle5 >=0.0.11
    - setuptools
    - seaborn
    - pyyaml
    - scikit-image
    - matplotlib-base
    - requests
    - libvips
    - pyvips
    - pytest
    - python >=3.6
    - torchvision
    - deprecated >=1.2.5
    - medcam
    - opencv
    - psutil
    - coverage
    - SimpleITK >=2.1.0
    - pytest-azurepipelines
    - pkgconfig
    - torchmetrics ==0.5.1
    - tiffslide
    - pydicom
    - OpenPatchMiner ==0.1.8
    - onnx

test:
  imports:
    - GANDLF
    - GANDLF.utils
    - GANDLF.models
    - GANDLF.compute

about:
  home: https://github.com/CBICA/GaNDLF
  license: LicenseRef-CBICA
  license_family: BSD
  license_file: LICENSE
  summary: The Generally Nuanced Deep Learning Framework for segmentation, regression and classification.
  doc_url: https://cbica.github.io/GaNDLF/
  dev_url: https://cbica.github.io/GaNDLF/extending

extra:
  recipe-maintainers:
    - sarthakpati
