{% set name = "gandlf" %}
{% set version = "0.1.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b83457541c970c52f5b1b3203ee7e1f6611c86be3b9e0eac18f51a5a3fd9cbe0

build:
  entry_points:
    - gandlf=GANDLF.entrypoints.cli_tool:gandlf
    - gandlf_run=GANDLF.entrypoints.run:old_way
    - gandlf_constructCSV=GANDLF.entrypoints.construct_csv:old_way
    - gandlf_collectStats=GANDLF.entrypoints.collect_stats:old_way
    - gandlf_patchMiner=GANDLF.entrypoints.patch_miner:old_way
    - gandlf_preprocess=GANDLF.entrypoints.preprocess:old_way
    - gandlf_anonymizer=GANDLF.entrypoints.anonymizer:old_way
    - gandlf_configGenerator=GANDLF.entrypoints.config_generator:old_way
    - gandlf_verifyInstall=GANDLF.entrypoints.verify_install:old_way
    - gandlf_recoverConfig=GANDLF.entrypoints.recover_config:old_way
    - gandlf_deploy=GANDLF.entrypoints.deploy:old_way
    - gandlf_optimizeModel=GANDLF.entrypoints.optimize_model:old_way
    - gandlf_generateMetrics=GANDLF.entrypoints.generate_metrics:old_way
    - gandlf_debugInfo=GANDLF.entrypoints.debug_info:old_way
    - gandlf_splitCSV=GANDLF.entrypoints.split_csv:old_way
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.12
    - pytorch ==2.7.1
    - black ==23.11.0
    - lightning ==2.5.2
    - numpy ==1.26.4
    - scipy
    - simpleitk !=2.0.*,!=2.2.1
    - torchvision
    - tqdm
    - torchio ==0.19.6
    - pandas >=2.0.0
    - scikit-learn >=0.23.2
    - scikit-image >=0.19.1
    - setuptools
    - seaborn
    - pyyaml
    - matplotlib-base
    - gdown ==5.1.0
    - overrides ==7.7.0
    - pytest
    - coverage
    - pytest-cov
    - psutil
    - medcam
    - opencv
    - torchmetrics ==1.1.2
    - zarr ==2.10.3
    - pydicom
    - onnx
    - torchinfo ==1.7.0
    - segmentation-models-pytorch ==0.4.0
    - acsconv ==0.1.1
    - requests >=2.32.2
    - docker-py
    - dicom-anonymizer ==1.0.12
    - twine
    - keyring
    - monai ==1.4.0
    - click ==8.1.8
    - deprecated
    - packaging ==24.0
    - typer ==0.9.0
    - colorlog
    - opacus ==1.5.2
    - huggingface_hub ==0.25.1
    - openslide >=4.0.0
    - openslide-python ==1.4.1
    - lion-pytorch ==0.2.2
    - pydantic ==2.10.6
    - panoptica >=1.4.1
    - typer >=0.15.0

test:
  imports:
    - GANDLF
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mlcommons.github.io/GaNDLF/
  summary: PyTorch-based framework that handles segmentation/regression/classification using various DL architectures for medical imaging.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mlcommons.github.io/GaNDLF/
  dev_url: https://mlcommons.github.io/GaNDLF/extending/

extra:
  recipe-maintainers:
    - AlexanderGetka-cbica
    - sarthakpati
