{% set name = "gandlf" %}
{% set version = "0.0.2020240727" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 812ea1abce6e89f7ce10196da41d89360d185a316cc409085575d1b65807508b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >3.8,<3.12
  run:
    - acsconv ==0.1.1
    - black ==23.11.0
    - coverage
    - dicom-anonymizer ==1.0.12
    - docker-py
    - gdown ==5.1.0
    - keyring
    - matplotlib-base
    - medcam
    - monai ==1.3.0
    - numpy ==1.25.0
    - onnx
    - opencv
    - pandas >=2.0.0
    - psutil
    - pydicom
    - pytest
    - pytest-cov
    - python >3.8,<3.12
    - pyyaml
    - pytorch ==2.1.2
    - pydeprecate
    - scikit-image >=0.19.1
    - scikit-learn >=0.23.2
    - scipy
    - seaborn
    - segmentation-models-pytorch ==0.3.3
    - setuptools
    - simpleitk !=2.0.*,!=2.2.1
    - torchinfo ==1.7.0
    - torchio ==0.19.5
    - torchmetrics ==1.1.2
    - torchvision
    - typer
    - tiffslide
    - tqdm
    - twine
    - zarr ==2.10.3

test:
  imports:
    - GANDLF
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://mlcommons.github.io/GaNDLF/
  summary: PyTorch-based framework that handles segmentation/regression/classification using various DL architectures for medical imaging.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mlcommons.github.io/GaNDLF/
  dev_url: https://mlcommons.github.io/GaNDLF/extending/

extra:
  recipe-maintainers:
    - AlexanderGetka-cbica
    - sarthakpati
