{% set name = "gandlf" %}
{% set version = "0.0.16.dev20230403" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GANDLF-{{ version }}.tar.gz
  sha256: e6a910647762acd05f93efd3ac52bc117570ac6164264da1544d3c3c9a577511

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - acsconv ==0.1.1
    - black
    - coverage
    - dicom-anonymizer
    - docker-py
    - keyring
    - matplotlib-base
    - medcam
    - numpy ==1.22.0
    - onnx
    - opencv
    - openpatchminer ==0.1.8
    - pandas
    - psutil
    - pydicom
    - pytest
    - pytest-cov
    - python >=3.8
    - pyyaml
    - requests >=2.25.0
    - scikit-image >=0.19.1
    - scikit-learn >=0.23.2
    - scipy
    - seaborn
    - segmentation-models-pytorch ==0.3.0
    - setuptools
    - simpleitk !=2.0.*
    - tiffslide
    - pytorch ==1.13.1
    - torchinfo ==1.7.0
    - torchio ==0.18.75
    - torchmetrics ==0.5.1
    - torchvision
    - tqdm
    - twine
    - zarr ==2.10.3

test:
  imports:
    - GANDLF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mlcommons.github.io/GaNDLF/
  summary: PyTorch-based framework that handles segmentation/regression/classification using various DL architectures for medical imaging.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mlcommons.github.io/GaNDLF/
  dev_url: https://mlcommons.github.io/GaNDLF/extending/

extra:
  recipe-maintainers:
    - AlexanderGetka-cbica
    - sarthakpati
